# Copyright (C) 2018 NVIDIA Corporation.  All rights reserved.
# Licensed under the CC BY-NC-SA 4.0 license (https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode).

# logger options
image_save_iter: 1000         # How often do you want to save output images during training
snapshot_save_iter: 10000     # How often do you want to save trained models
log_iter: 10                  # How often do you want to log the training stats

# optimization options
total_iterations: 200000
batch_size: 8
num_workers: 1
weight_decay: 0
beta1: 0
beta2: 0.99
init: kaiming
lr_dis: 0.0001
lr_gen_mappers: 0.000001
lr_gen_others: 0.0001

#
adv_w: 1
sty_w: 1
rec_w: 1
cls_w: 1
ort_w: 0.001

style_dim: 256
noise_dim: 32

discriminators:
  # No normalization (Attribute-specific)
  channels: [64, 128, 256, 512, 1024, 2048]
extractors:
  # No normalization (Tag-specific)
  channels: [64, 128, 256, 512, 1024, 2048]
encoder:
  # Instance Normalization (Shared)
  channels: [64, 128, 256]
translators:
  # Adaptive Instance Normalization (Tag-specific)
  channels: [64, 64, 64, 64, 64, 64, 64, 64]
decoder:
   # Instance Normalization (Shared)
  channels: [256, 128, 256, 64]
mappers:
  # No normalization (Attribute-specific)
  # Last num of pre_channels should be equal to the first num of post_channels
  pre_channels: [256, 256, 256]
  post_channels: [256, 256, 256]

tags:
  -
    name: emotion
    tag_irrelevant_conditions_dim: 1
    attributes:
      -
        name: 'angry'
        filename: ./datasets/emotion_angry.txt
      -
        name: 'contemptuous'
        filename: ./datasets/emotion_contemptuous.txt
      -
        name: 'disgusted'
        filename: ./datasets/emotion_disgusted.txt
      -
        name: 'fearful'
        filename: ./datasets/emotion_fearful.txt
      -
        name: 'happy'
        filename: ./datasets/emotion_happy.txt
      -
        name: 'neutral'
        filename: ./datasets/emotion_neutral.txt
      -
        name: 'sad'
        filename: ./datasets/emotion_sad.txt
      -
        name: 'surprise'
        filename: ./datasets/emotion_surprise.txt


# data options
input_dim: 3                  # number of image channels
new_size: 128                 # first resize the shortest image side to this size
crop_image_height: 128        # random crop image of this height
crop_image_width: 128        # random crop image of this width

